name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRETO }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependecias
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploly to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          app_location: 'public'
          deployment_action: "upload"
      